### ISSUE TITLE
Question about this scripts

### ISSUE THREAD

**Issue by DevX-Cipher** [univ-of-utah-marriott-library-apple/firmware_password_manager#9]
hi just want to ask a few questions about the older version and the new version I see in the new version you can delete the firmware password if one is set but I don't see it in the older version can you please explain also can we not include a way to right the current password to a text file just out curiosity

**Comment by uurazzle** [comment]
HI @modz2014,

I apologize for the inconvenience you are experiencing. Unfortunately, due to limitations in IT resources, time constraints, and competing priorities, we were unable to incorporate all the new features of the latest version of the Firmware Password Manager (FWPM) into the older version.

To access the desired functionality, I would strongly recommend upgrading to the newer version. This will ensure that you have access to the necessary features and improvements.

Thank you for your understanding.

Best regards,
